### ISSUE TITLE
Why all the time outs ?

### ISSUE THREAD

**Issue by idantb101** [OfirShukrun/Weather-app#6]
https://github.com/OfirShukrun/Weather-app/blob/91ec43570cc4449a67eab8e52904f0c744cb120e/app.js#L66

**Comment by OfirShukrun** [comment]
becase I was trying to do the animation after you get the data from the API. this is working fine.

**Comment by idantb101** [comment]
no no no no no, just put it in the callback 😞

**Comment by OfirShukrun** [comment]
dammm...but it works fine XD

**Comment by OfirShukrun** [comment]
wait....Ive been trying with callbacks but it wont work....
